### ISSUE TITLE
Travis misconfigured, status failing

### ISSUE THREAD

**Issue by ismaro3** [UNIZAR-30246-WebEngineering/UrlShortener2015#12]
Repo travis status is fail, in spite of being correct.
It is because you have modified or create a branch and "Build only if travis.yml is present" option is not checked, so Travis tries to test the new branches without success.

To fix it, please go to your repository configuration in travis and check "Build only if travis.yml is present", as shown in the image:
![screenshot - 090116 - 20 38 59](https://cloud.githubusercontent.com/assets/628371/12217973/254aa310-b711-11e5-9484-3cab0db75fd0.png)

**Comment by fjlopez** [comment]
Fixed! (+1 Bug Hunting)
