### ISSUE TITLE
Wiki "errors"

### ISSUE THREAD

**Issue by MarcosCM** [UNIZAR-30246-WebEngineering/UrlShortener2015#2]
Please, head to the [wiki](https://github.com/UNIZAR-30246-WebEngineering/UrlShortener2015/wiki).
In the 9th step, the name of the gradle file which is in the demo folder is **build.gradle** (not gradle.build). The name of this gradle file in the specific projects with a fancy name should also be build.gradle (at least as of gradle 2.8). If its name is not **build.gradle** then gradle may throw an error.
There's also a typo regarding the second line in that step (starting like _pgradle.build file..._), which produces a style issue. I guess it should be:
```
`build.gradle` file. For example if your project is _BangladeshGreen_ you must set it to `urlshortener2015.bangladeshgreen.Application`
```
which would look like:
`build.gradle` file. For example if your project is _BangladeshGreen_ you must set it to `urlshortener2015.bangladeshgreen.Application`

**Comment by fjlopez** [comment]
Fixed. I just rewarded you with +1 in the bug hunting race.
